import type { Metadata } from 'next';
import './app.scss';
import AppProvider from '@/components/AppProvider/AppProvider';
export const metadata: Metadata = {
  title: 'Schrek',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          {children}
      </body>
    </html>
  );
}
